name: steam_discount_adviser
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

platforms:
  linux:
  macos:
  windows:  

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  test: ^1.21.1
  dio: ^4.0.6
  multi_split_view: ^2.1.0
  local_notifier: ^0.1.5
  path_provider: ^2.0.11
  sqflite: ^2.1.0
  provider: ^6.0.3
  cron: ^0.5.0
  sqflite_common_ffi: ^2.2.0+1
  window_manager: ^0.2.7
  tray_manager: ^0.2.0
  dartdoc: ^6.1.1
  mockito: ^5.3.2
  connectivity_plus: ^3.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  #dart_code_metrics: ^5.6.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/games_manager.db
    - assets/images/app_icon_128.png

  fonts:
    - family: RobotoMono
      fonts:
        - asset: font/RobotoMono-Regular.ttf
    - family: TrashBinIcon
      fonts:
        - asset: font/TrashBinIcon.ttf
  